#!/usr/bin/env php
<?php

use Illuminate\Container\Container;
use Lucid\Console\Commands\NewCommand;
use Lucid\Console\Commands\ServiceMakeCommand;
use Lucid\Console\Commands\ControllerMakeCommand;

require __DIR__.'/../../bootstrap/autoload.php';
$app = require __DIR__.'/../../bootstrap/app.php';

$kernel = $app->make(Lucid\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

$kernel->terminate($input, $status);

exit($status);
